### ISSUE TITLE
version missing -SNAPSHOT, isSnapshot always false

### ISSUE THREAD

**Issue by amesgen** [djspiewak/sbt-spiewak#44]
For example, for `cats-effect-testing` on `series/0.x`:

```
sbt:cats-effect-testing> show isSnapshot
[info] minitest / isSnapshot
[info] 	false
[info] scalatest-scalacheck / isSnapshot
[info] 	false
[info] scalatest / isSnapshot
[info] 	false
[info] utest / isSnapshot
[info] 	false
[info] specs2 / isSnapshot
[info] 	false
[info] isSnapshot
[info] 	false
sbt:cats-effect-testing> show version
[info] minitest / version
[info] 	0.5-3-78ce2ad
[info] scalatest-scalacheck / version
[info] 	0.5-3-78ce2ad
[info] scalatest / version
[info] 	0.5-3-78ce2ad
[info] utest / version
[info] 	0.5-3-78ce2ad
[info] specs2 / version
[info] 	0.5-3-78ce2ad
[info] version
[info] 	0.5-3-78ce2ad
```

Is this expected?

---

In http4s-jdk-http-client, we use `isSnapshot` to publish snapshot documentation in a specific directory:

https://github.com/http4s/http4s-jdk-http-client/blob/1910a08dfeddef8e30062fab7dd06b6c3e71fa59/build.sbt#L181-L183

**Comment by djspiewak** [comment]
This is by design. :-) If you modify some file (so that you have a dirty git state) and then `reload`, you'll see `isSnapshot` set to `true`, and `version` will have the appropriate suffix. The philosophy here is that hash "snapshots" are in fact stable, and therefore they don't correspond with Maven's notion of "snapshot", thus `isSnapshot := false`.

**Comment by amesgen** [comment]
Ah, thanks for the clarification! This makes perfect sense, even though I am not used to this approach Ü
